// Castle (囲い) formation data
// Each castle defines piece positions on a 9x9 board
// owner: 1 = player (bottom side)

export const CASTLE_CATEGORIES = [
  {
    id: 'ibisha',
    name: '居飛車向けの囲い',
    nameKids: 'いびしゃむけの かこい',
    subcategories: [
      {
        id: 'yagura',
        name: '矢倉系',
        nameKids: 'やぐらけい',
        castles: [
          {
            id: 'yagura',
            name: '矢倉囲い',
            nameKids: 'やぐらがこい',
            description: '居飛車の代表的な囲い。上部からの攻めに強い。',
            descriptionKids: 'いびしゃの だいひょうてきな かこい。うえからの せめに つよい。',
            pieces: [
              { type: 'king', row: 8, col: 1, owner: 1 },
              { type: 'gold', row: 7, col: 2, owner: 1 },
              { type: 'gold', row: 6, col: 3, owner: 1 },
              { type: 'silver', row: 6, col: 2, owner: 1 },
              { type: 'knight', row: 8, col: 0, owner: 1 },
              { type: 'lance', row: 8, col: 8, owner: 1 },
              { type: 'pawn', row: 7, col: 0, owner: 1 },
              { type: 'pawn', row: 7, col: 1, owner: 1 },
              { type: 'pawn', row: 5, col: 2, owner: 1 },
              { type: 'pawn', row: 5, col: 3, owner: 1 },
            ],
          },
          {
            id: 'katayagura',
            name: '片矢倉',
            nameKids: 'かたやぐら',
            description: '矢倉の変形。王が7八にいる形。手数が少なく組める。',
            descriptionKids: 'やぐらの へんけい。おうが ななはちに いるかたち。てすうが すくなく くめる。',
            pieces: [
              { type: 'king', row: 7, col: 1, owner: 1 },
              { type: 'gold', row: 7, col: 2, owner: 1 },
              { type: 'gold', row: 6, col: 3, owner: 1 },
              { type: 'silver', row: 6, col: 2, owner: 1 },
              { type: 'knight', row: 8, col: 0, owner: 1 },
              { type: 'lance', row: 8, col: 8, owner: 1 },
              { type: 'pawn', row: 7, col: 0, owner: 1 },
              { type: 'pawn', row: 5, col: 2, owner: 1 },
              { type: 'pawn', row: 5, col: 3, owner: 1 },
            ],
          },
        ],
      },
      {
        id: 'hidarimino',
        name: '左美濃系',
        nameKids: 'ひだりみのけい',
        castles: [
          {
            id: 'hidarimino',
            name: '左美濃囲い',
            nameKids: 'ひだりみのがこい',
            description: '居飛車で使う美濃囲い。横からの攻めに強い。',
            descriptionKids: 'いびしゃで つかう みのがこい。よこからの せめに つよい。',
            pieces: [
              { type: 'king', row: 8, col: 1, owner: 1 },
              { type: 'gold', row: 7, col: 2, owner: 1 },
              { type: 'silver', row: 7, col: 1, owner: 1 },
              { type: 'knight', row: 8, col: 0, owner: 1 },
              { type: 'lance', row: 8, col: 8, owner: 1 },
              { type: 'pawn', row: 6, col: 0, owner: 1 },
              { type: 'pawn', row: 6, col: 1, owner: 1 },
              { type: 'pawn', row: 6, col: 2, owner: 1 },
            ],
          },
          {
            id: 'ten守閣',
            name: '天守閣美濃',
            nameKids: 'てんしゅかくみの',
            description: '左美濃の発展形。王が高い位置にいる。',
            descriptionKids: 'ひだりみのの はってんけい。おうが たかい いちに いる。',
            pieces: [
              { type: 'king', row: 7, col: 1, owner: 1 },
              { type: 'gold', row: 7, col: 2, owner: 1 },
              { type: 'silver', row: 6, col: 1, owner: 1 },
              { type: 'knight', row: 8, col: 0, owner: 1 },
              { type: 'lance', row: 8, col: 8, owner: 1 },
              { type: 'pawn', row: 6, col: 0, owner: 1 },
              { type: 'pawn', row: 5, col: 1, owner: 1 },
              { type: 'pawn', row: 6, col: 2, owner: 1 },
            ],
          },
        ],
      },
      {
        id: 'ibisha_other',
        name: '居飛車その他の囲い',
        nameKids: 'いびしゃ そのたの かこい',
        castles: [
          {
            id: 'funagakoi',
            name: '舟囲い',
            nameKids: 'ふながこい',
            description: '急戦向きの簡単な囲い。手数が少なく組める。',
            descriptionKids: 'きゅうせんむきの かんたんな かこい。てすうが すくなく くめる。',
            pieces: [
              { type: 'king', row: 8, col: 2, owner: 1 },
              { type: 'gold', row: 8, col: 3, owner: 1 },
              { type: 'silver', row: 7, col: 2, owner: 1 },
              { type: 'knight', row: 8, col: 0, owner: 1 },
              { type: 'lance', row: 8, col: 8, owner: 1 },
              { type: 'pawn', row: 6, col: 0, owner: 1 },
              { type: 'pawn', row: 6, col: 1, owner: 1 },
              { type: 'pawn', row: 6, col: 2, owner: 1 },
            ],
          },
          {
            id: 'elmo',
            name: 'elmo囲い',
            nameKids: 'えるもがこい',
            description: '金銀が横に並んだ現代的な囲い。バランスが良い。',
            descriptionKids: 'きんぎんが よこに ならんだ げんだいてきな かこい。ばらんすが よい。',
            pieces: [
              { type: 'king', row: 8, col: 1, owner: 1 },
              { type: 'gold', row: 7, col: 2, owner: 1 },
              { type: 'silver', row: 8, col: 2, owner: 1 },
              { type: 'knight', row: 8, col: 0, owner: 1 },
              { type: 'lance', row: 8, col: 8, owner: 1 },
              { type: 'pawn', row: 6, col: 0, owner: 1 },
              { type: 'pawn', row: 6, col: 1, owner: 1 },
              { type: 'pawn', row: 6, col: 2, owner: 1 },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 'furibisha',
    name: '振り飛車向けの囲い',
    nameKids: 'ふりびしゃむけの かこい',
    subcategories: [
      {
        id: 'mino',
        name: '美濃系の囲い',
        nameKids: 'みのけいの かこい',
        castles: [
          {
            id: 'mino',
            name: '美濃囲い',
            nameKids: 'みのがこい',
            description: '振り飛車の基本囲い。横からの攻めに強い。',
            descriptionKids: 'ふりびしゃの きほんの かこい。よこからの せめに つよい。',
            pieces: [
              { type: 'king', row: 8, col: 7, owner: 1 },
              { type: 'gold', row: 8, col: 5, owner: 1 },
              { type: 'silver', row: 7, col: 6, owner: 1 },
              { type: 'knight', row: 8, col: 8, owner: 1 },
              { type: 'lance', row: 8, col: 0, owner: 1 },
              { type: 'pawn', row: 6, col: 6, owner: 1 },
              { type: 'pawn', row: 6, col: 7, owner: 1 },
              { type: 'pawn', row: 6, col: 8, owner: 1 },
            ],
          },
          {
            id: 'takamino',
            name: '高美濃囲い',
            nameKids: 'たかみのがこい',
            description: '美濃囲いの発展形。上部にも強くなる。',
            descriptionKids: 'みのがこいの はってんけい。うえにも つよくなる。',
            pieces: [
              { type: 'king', row: 8, col: 7, owner: 1 },
              { type: 'gold', row: 7, col: 6, owner: 1 },
              { type: 'gold', row: 8, col: 5, owner: 1 },
              { type: 'silver', row: 6, col: 5, owner: 1 },
              { type: 'knight', row: 8, col: 8, owner: 1 },
              { type: 'lance', row: 8, col: 0, owner: 1 },
              { type: 'pawn', row: 6, col: 6, owner: 1 },
              { type: 'pawn', row: 6, col: 7, owner: 1 },
              { type: 'pawn', row: 6, col: 8, owner: 1 },
            ],
          },
          {
            id: 'ginkanmuri',
            name: '銀冠',
            nameKids: 'ぎんかんむり',
            description: '美濃囲いからさらに発展。銀が高い位置で守る。',
            descriptionKids: 'みのがこいから さらに はってん。ぎんが たかい いちで まもる。',
            pieces: [
              { type: 'king', row: 8, col: 7, owner: 1 },
              { type: 'gold', row: 7, col: 6, owner: 1 },
              { type: 'gold', row: 8, col: 5, owner: 1 },
              { type: 'silver', row: 6, col: 7, owner: 1 },
              { type: 'knight', row: 8, col: 8, owner: 1 },
              { type: 'lance', row: 8, col: 0, owner: 1 },
              { type: 'pawn', row: 5, col: 6, owner: 1 },
              { type: 'pawn', row: 5, col: 7, owner: 1 },
              { type: 'pawn', row: 6, col: 8, owner: 1 },
            ],
          },
        ],
      },
      {
        id: 'anaguma',
        name: '穴熊系の囲い',
        nameKids: 'あなぐまけいの かこい',
        castles: [
          {
            id: 'furibisha_anaguma',
            name: '振り飛車穴熊',
            nameKids: 'ふりびしゃ あなぐま',
            description: '非常に堅い囲い。王を隅に配置して金銀で固める。',
            descriptionKids: 'とても かたい かこい。おうを すみに おいて きんぎんで かためる。',
            pieces: [
              { type: 'king', row: 8, col: 8, owner: 1 },
              { type: 'gold', row: 7, col: 7, owner: 1 },
              { type: 'silver', row: 7, col: 8, owner: 1 },
              { type: 'lance', row: 8, col: 0, owner: 1 },
              { type: 'pawn', row: 6, col: 6, owner: 1 },
              { type: 'pawn', row: 6, col: 7, owner: 1 },
              { type: 'pawn', row: 6, col: 8, owner: 1 },
            ],
          },
          {
            id: 'ibisha_anaguma',
            name: '居飛車穴熊',
            nameKids: 'いびしゃ あなぐま',
            description: '居飛車からも使える穴熊。とても堅い。',
            descriptionKids: 'いびしゃからも つかえる あなぐま。とても かたい。',
            pieces: [
              { type: 'king', row: 8, col: 0, owner: 1 },
              { type: 'gold', row: 7, col: 1, owner: 1 },
              { type: 'silver', row: 7, col: 0, owner: 1 },
              { type: 'lance', row: 8, col: 8, owner: 1 },
              { type: 'pawn', row: 6, col: 0, owner: 1 },
              { type: 'pawn', row: 6, col: 1, owner: 1 },
              { type: 'pawn', row: 6, col: 2, owner: 1 },
            ],
          },
        ],
      },
      {
        id: 'furibisha_other',
        name: '振り飛車その他の囲い',
        nameKids: 'ふりびしゃ そのたの かこい',
        castles: [
          {
            id: 'katamino',
            name: '片美濃囲い',
            nameKids: 'かたみのがこい',
            description: '美濃囲いの簡略版。金1枚で素早く組める。',
            descriptionKids: 'みのがこいの かんりゃくばん。きん1まいで すばやく くめる。',
            pieces: [
              { type: 'king', row: 8, col: 7, owner: 1 },
              { type: 'silver', row: 7, col: 6, owner: 1 },
              { type: 'knight', row: 8, col: 8, owner: 1 },
              { type: 'lance', row: 8, col: 0, owner: 1 },
              { type: 'pawn', row: 6, col: 6, owner: 1 },
              { type: 'pawn', row: 6, col: 7, owner: 1 },
              { type: 'pawn', row: 6, col: 8, owner: 1 },
            ],
          },
          {
            id: 'kinkaburi',
            name: '金無双',
            nameKids: 'きんむそう',
            description: '相振り飛車で使われる囲い。金2枚が横に並ぶ。',
            descriptionKids: 'あいふりびしゃで つかわれる かこい。きん2まいが よこに ならぶ。',
            pieces: [
              { type: 'king', row: 8, col: 7, owner: 1 },
              { type: 'gold', row: 7, col: 6, owner: 1 },
              { type: 'gold', row: 7, col: 5, owner: 1 },
              { type: 'silver', row: 6, col: 6, owner: 1 },
              { type: 'knight', row: 8, col: 8, owner: 1 },
              { type: 'lance', row: 8, col: 0, owner: 1 },
              { type: 'pawn', row: 6, col: 7, owner: 1 },
              { type: 'pawn', row: 6, col: 8, owner: 1 },
            ],
          },
        ],
      },
    ],
  },
];
